"""empty message

Revision ID: 04e4bba17688
Revises: 086a724aea12
Create Date: 2024-09-30 11:04:15.658572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04e4bba17688'
down_revision = '086a724aea12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entidades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entidades', schema=None) as batch_op:
        batch_op.drop_column('tipo')

    # ### end Alembic commands ###
