"""empty message

Revision ID: 086a724aea12
Revises: ebbeed7cb18b
Create Date: 2024-09-28 14:40:59.832669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '086a724aea12'
down_revision = 'ebbeed7cb18b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entidades')
    # ### end Alembic commands ###
