"""empty message

Revision ID: 08a5374fdcfa
Revises: a4a2423f1776
Create Date: 2024-10-04 13:22:19.621351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08a5374fdcfa'
down_revision = 'a4a2423f1776'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inscripciones', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'eventos', ['evento_id'], ['id'])
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inscripciones', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
