"""empty message

Revision ID: 37f643f048b5
Revises: 5d9713fa07b8
Create Date: 2024-10-11 19:04:24.591019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37f643f048b5'
down_revision = '5d9713fa07b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eventos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('partner_nombre', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eventos', schema=None) as batch_op:
        batch_op.drop_column('partner_nombre')

    # ### end Alembic commands ###
