"""empty message

Revision ID: 3c191acd7ab7
Revises: 5df15010c229
Create Date: 2024-10-09 19:30:31.564985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c191acd7ab7'
down_revision = '5df15010c229'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eventos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('direccion', sa.String(length=255), nullable=True))
        batch_op.drop_column('ciudad')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eventos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ciudad', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.drop_column('direccion')

    # ### end Alembic commands ###
