"""empty message

Revision ID: 3efc5b32d030
Revises: cbb0e0ada59f
Create Date: 2024-10-07 14:49:18.287429

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3efc5b32d030'
down_revision = 'cbb0e0ada59f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eventos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('partner_id', sa.Integer(), nullable=True))
        batch_op.alter_column('fecha',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('hora_inicio',
               existing_type=postgresql.TIME(),
               nullable=True)
        batch_op.alter_column('hora_fin',
               existing_type=postgresql.TIME(),
               nullable=True)
        batch_op.alter_column('ciudad',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('codigo_postal',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('breve_descripcion',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('accesibilidad',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('dificultad',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('precio',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('cupo',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('observaciones',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.create_foreign_key(None, 'partners', ['partner_id'], ['id'])

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('direccion', sa.String(length=255), nullable=True))
        batch_op.alter_column('foto',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('foto_perfil',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_column('ciudad')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ciudad', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.alter_column('foto_perfil',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('foto',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('direccion')

    with op.batch_alter_table('eventos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('observaciones',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('cupo',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('precio',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('dificultad',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('accesibilidad',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('breve_descripcion',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('codigo_postal',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('ciudad',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('hora_fin',
               existing_type=postgresql.TIME(),
               nullable=False)
        batch_op.alter_column('hora_inicio',
               existing_type=postgresql.TIME(),
               nullable=False)
        batch_op.alter_column('fecha',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.drop_column('partner_id')

    # ### end Alembic commands ###
