"""empty message

Revision ID: 4039a60835b8
Revises: 04e4bba17688
Create Date: 2024-09-30 12:12:52.184860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4039a60835b8'
down_revision = '04e4bba17688'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entidades', schema=None) as batch_op:
        batch_op.alter_column('tipo',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entidades', schema=None) as batch_op:
        batch_op.alter_column('tipo',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
