"""empty message

Revision ID: 6d7ed3910df9
Revises: e18260a34b51
Create Date: 2024-10-06 10:05:49.263357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d7ed3910df9'
down_revision = 'e18260a34b51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('imagenes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('es_perfil', sa.Boolean(), nullable=True))

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto_perfil', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('foto_perfil')

    with op.batch_alter_table('imagenes', schema=None) as batch_op:
        batch_op.drop_column('es_perfil')

    # ### end Alembic commands ###
