"""empty message

Revision ID: 78f7f1ba278c
Revises: d4513b0704ab
Create Date: 2024-10-10 23:04:05.816272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78f7f1ba278c'
down_revision = 'd4513b0704ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partners', schema=None) as batch_op:
        batch_op.add_column(sa.Column('direccion', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('latitud', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitud', sa.Float(), nullable=True))
        batch_op.drop_column('ciudad')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partners', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ciudad', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.drop_column('longitud')
        batch_op.drop_column('latitud')
        batch_op.drop_column('direccion')

    # ### end Alembic commands ###
