"""empty message

Revision ID: 863aaf1f8565
Revises: 64ac1bd1c1c6
Create Date: 2024-10-05 08:04:42.146341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '863aaf1f8565'
down_revision = '64ac1bd1c1c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('foto')

    # ### end Alembic commands ###
