"""empty message

Revision ID: a713464df9bf
Revises: 9e5c4f737ff5
Create Date: 2024-10-02 10:12:44.475210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a713464df9bf'
down_revision = '9e5c4f737ff5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entidades', schema=None) as batch_op:
        batch_op.drop_constraint('entidades_nombre_key', type_='unique')
        batch_op.drop_column('nombre')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entidades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('entidades_nombre_key', ['nombre'])

    # ### end Alembic commands ###
