"""empty message

Revision ID: d4513b0704ab
Revises: 1998ceb353d8
Create Date: 2024-10-10 19:30:43.505485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4513b0704ab'
down_revision = '1998ceb353d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('imagenes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('partner_email', sa.String(length=120), nullable=True))
        batch_op.alter_column('usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'partners', ['partner_email'], ['email'])

    with op.batch_alter_table('partners', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('foto_perfil', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partners', schema=None) as batch_op:
        batch_op.drop_column('foto_perfil')
        batch_op.drop_column('foto')

    with op.batch_alter_table('imagenes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('partner_email')

    # ### end Alembic commands ###
