"""empty message

Revision ID: e673992d8676
Revises: f0498eac90b4
Create Date: 2024-10-15 19:24:15.769628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e673992d8676'
down_revision = 'f0498eac90b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('telefono')
        batch_op.drop_column('genero')

    with op.batch_alter_table('usuarios_intereses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interes_id', sa.Integer(), nullable=False))
        batch_op.alter_column('usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('usuarios_intereses_intereses_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'intereses', ['interes_id'], ['id'])
        batch_op.drop_column('intereses_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios_intereses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('intereses_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('usuarios_intereses_intereses_id_fkey', 'intereses', ['intereses_id'], ['id'])
        batch_op.alter_column('usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('interes_id')

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genero', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('telefono', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
